const List<String> combustibles = [
  'Adblue',
  'Amoniaco',
  'Biodiesel',
  'Bioetanol',
  'Biogas Natural Comprimido',
  'Biogas Natural Licuado',
  'Diésel Renovable',
  'Gas Natural Comprimido',
  'Gas Natural Licuado',
  'Gases licuados del petróleo',
  'Gasoleo A',
  'Gasoleo B',
  'Gasoleo Premium',
  'Gasolina 95 E10',
  'Gasolina 95 E25',
  'Gasolina 95 E5',
  'Gasolina 95 E5 Premium',
  'Gasolina 95 E85',
  'Gasolina 98 E10',
  'Gasolina 98 E5',
  'Gasolina Renovable',
  'Hidrogeno',
  'Metanol',
]; 